### ISSUE TITLE
Win7 dragging the application window to the lower right corner will automatically disconnect

### ISSUE THREAD

**Issue by duxubo** [wwt/guac-vue#14]
Hello, remote connection win7 dragging the application window to the lower right corner will automatically disconnect, please fix it, thank you very much.

**Comment by jakecoffman** [comment]
This is probably an issue with guacd or FreeRDP incompatibility with Win7. Start by checking with the Apache Guacamole project https://guacamole.apache.org/ and see if any one else is having that issue.
