### ISSUE TITLE
出现异常错误，作者看一哈。

### ISSUE THREAD

**Issue by likujy2061** [wwt/guac-vue#8]
你好，在使用该源代码配合你发布的客户端后，遭遇了无法连接至guacd，报错情况如图。您在开发这个项目时请问能正常运行吗？
我已经检查了guacd的相关配置，均正常，不知道为什么会遭遇这种情况。您能指导一哈吗
time="2021-02-24T15:20:34+08:00" level=error msg="error while connecting to guacd dial tcp 10.10.4.62:4822: connectex: No connection could be made because the target machine actively refused it."

![image](https://user-images.githubusercontent.com/26838977/108963310-e601ca80-76b4-11eb-99ca-a901f1d5ddfd.png)

![image](https://user-images.githubusercontent.com/26838977/108963212-c7033880-76b4-11eb-8b15-476424a903b5.png)

**Comment by jakecoffman** [comment]
Check to make sure there are no firewalls blocking the connection.

We usually run the guac client and guacd in the same container so we haven't seen any connection issues between them.

**Comment by likujy2061** [comment]
hello,wwt，Can you help me? Thank you &nbsp;！
Following your help, I have switched to docker container. But there are new problems. I can't connect, and vue prompts me to check the log  and client  error。 
guac-vue

guac






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wwt/guac-vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 晚上9:17
收件人:&nbsp;"wwt/guac-vue"<guac-vue@noreply.github.com&gt;;
抄送:&nbsp;"1405161366"<1405161366@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wwt/guac-vue] 出现异常错误，作者看一哈。 (#8)





 
Check to make sure there are no firewalls blocking the connection.
 
We usually run the guac client and guacd in the same container so we haven't seen any connection issues between them.
